version: '3'

services:
  api:
    build: .
    container_name: function-api
    ports:
      - "25100:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production